only-show-the-red-underline-if-both-yellow-and-red-are-present
korbit-ai/python-lsp-server pull request #4
Opened 2022-06-17 16:45 UTC by farfaraji

2022-06-17 17:17 UTC, aterrel requested changes
Can you add an accompanying test to the fix?

2022-06-17 17:32 UTC, aterrel commented on pylsp/python_lsp.py
> +                       lint['range']['start']['line'] == error['range']['end']['line']:
What if you have an error between the lint? Shouldn't this be:

```
lint_start, lint_end = lint['range']['start']['line'],  lint['range']['end']['line']
error_start, error_end = error['range']['start']['line'],  error['range']['end']['line'] 
if error_start <= lint_end <= error_end or \
    error_start <= lint_start <= error_end:
```

also seems like you have a race condition, what if the lint comes before the error? perhaps you want :

```
errors = [lint in lints if lint['severity'] == lsp.DiagnosticSeverity.Error]
new_lints = []
for lint in lints:
    for  error in errors:
        lint_start, lint_end = lint['range']['start']['line'],  lint['range']['end']['line']
        error_start, error_end = error['range']['start']['line'],  error['range']['end']['line'] 
        if not (error_start <= lint_end <= error_end or error_start <= lint_start <= error_end):    
            new_lints.append(lint)
```

2022-06-21 19:11 UTC, antoineKorbit commented on pylsp/python_lsp.py
> +        #             new_lints.append(lint)
Delete ?

2022-06-21 19:18 UTC, antoineKorbit requested changes

2022-06-21 19:18 UTC, antoineKorbit commented on pylsp/python_lsp.py
> +    errors = [lint for lint in lints if lint['severity'] == lsp.DiagnosticSeverity.Error]
So we filter out non `lsp.DiagnosticSeverity.Error`, what are the other types of possibilities that we want to ignore here?

2022-06-21 19:18 UTC, antoineKorbit commented on pylsp/python_lsp.py
> +    errors = [lint for lint in lints if lint['severity'] == lsp.DiagnosticSeverity.Error]
Does it mean that we aren't showing yellow highlight ? Or is it just for the one that are on the same line ?

2022-06-21 19:18 UTC, antoineKorbit commented on pylsp/python_lsp.py
> +    errors = [lint for lint in lints if lint['severity'] == lsp.DiagnosticSeverity.Error]
Should you add a test to make sure that on 2 different lines, we are still showing the `lsp.DiagnosticSeverity.Warning` ?

2022-06-21 19:19 UTC, aterrel approved these changes

2022-06-21 19:37 UTC, antoineKorbit approved these changes

2022-06-21 19:42 UTC, merged